### ISSUE TITLE
Saving Settings (When modal is closed)

### ISSUE THREAD

**Issue by KaizokuBento** [theCanadianHat/AvaburArmoryFilter#8]
When you setup the filters in the armory and you close the clan window and open it again the filters you filled in are reset and you have to fill in the filters again. Would be great if they could be saved on closing the clan window.

**Comment by theCanadianHat** [comment]
Thanks for the input. Keeping the filter settings in the same session will be possible and easy to do. As for saving the settings from session to session is already planned. 

Thanks again. I'll let you know when this has been implemented!

**Comment by theCanadianHat** [comment]
I have removed the reset on armory close for filter criteria. Make sure you get v1.4.2
